//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Free_Book.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceBook {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceBook() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Free_Book.Resources.ResourceBook", typeof(ResourceBook).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ فئه جديده.
        /// </summary>
        public static string btnSaveNewCategories {
            get {
                return ResourceManager.GetString("btnSaveNewCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string btnSaveNewPassword {
            get {
                return ResourceManager.GetString("btnSaveNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضف مجموعه مستحدمين.
        /// </summary>
        public static string btnSaveNewRole {
            get {
                return ResourceManager.GetString("btnSaveNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضف مستحدم جديد.
        /// </summary>
        public static string btnSaveNewUser {
            get {
                return ResourceManager.GetString("btnSaveNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغير الرقم السري.
        /// </summary>
        public static string ChangPassword {
            get {
                return ResourceManager.GetString("ChangPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاحداث.
        /// </summary>
        public static string InEvents {
            get {
                return ResourceManager.GetString("InEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العمليه.
        /// </summary>
        public static string LableActionName {
            get {
                return ResourceManager.GetString("LableActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعه الفئات.
        /// </summary>
        public static string LableCategories {
            get {
                return ResourceManager.GetString("LableCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفئه.
        /// </summary>
        public static string LableCategoryName {
            get {
                return ResourceManager.GetString("LableCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ العمليه.
        /// </summary>
        public static string LableDate {
            get {
                return ResourceManager.GetString("LableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الفئه.
        /// </summary>
        public static string LableDescription {
            get {
                return ResourceManager.GetString("LableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم  الحفظ.
        /// </summary>
        public static string LableError {
            get {
                return ResourceManager.GetString("LableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الحذف .
        /// </summary>
        public static string LableErrorDelete {
            get {
                return ResourceManager.GetString("LableErrorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم التعديل .
        /// </summary>
        public static string LableErrorEdit {
            get {
                return ResourceManager.GetString("LableErrorEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد خطا في كلمه المرور او كلمه السر او كلاهما.
        /// </summary>
        public static string LableErrorLogin {
            get {
                return ResourceManager.GetString("LableErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحه الرئيسيه.
        /// </summary>
        public static string LableHomePage {
            get {
                return ResourceManager.GetString("LableHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمليات الفئات.
        /// </summary>
        public static string LableLogCategories {
            get {
                return ResourceManager.GetString("LableLogCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اداره الكتب.
        /// </summary>
        public static string LableMangeBook {
            get {
                return ResourceManager.GetString("LableMangeBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايمكن الحفظ هذا الاسم موجود بالفعل.
        /// </summary>
        public static string LableMsgDublicateNameCategory {
            get {
                return ResourceManager.GetString("LableMsgDublicateNameCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الحفظ.
        /// </summary>
        public static string LableMsgNotSaveNewCategory {
            get {
                return ResourceManager.GetString("LableMsgNotSaveNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تعديل الفئه.
        /// </summary>
        public static string LableMsgNotUpdateCategory {
            get {
                return ResourceManager.GetString("LableMsgNotUpdateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ فئه جديده بنجاح.
        /// </summary>
        public static string LableMsgSaveNewCategory {
            get {
                return ResourceManager.GetString("LableMsgSaveNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل الفئه.
        /// </summary>
        public static string LableMsgUpdateCategory {
            get {
                return ResourceManager.GetString("LableMsgUpdateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفئه.
        /// </summary>
        public static string LableNameCategory {
            get {
                return ResourceManager.GetString("LableNameCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعد كتابه الرقم السري الجديد.
        /// </summary>
        public static string LableNewComparPassword {
            get {
                return ResourceManager.GetString("LableNewComparPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل رقم سري جديد.
        /// </summary>
        public static string LableNewPassword {
            get {
                return ResourceManager.GetString("LableNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string LableRegister {
            get {
                return ResourceManager.GetString("LableRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المجموعه.
        /// </summary>
        public static string LableRoleName {
            get {
                return ResourceManager.GetString("LableRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعه المستخدمين.
        /// </summary>
        public static string LableRoles {
            get {
                return ResourceManager.GetString("LableRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل مجموعه المستخدمين.
        /// </summary>
        public static string LableRoleUser {
            get {
                return ResourceManager.GetString("LableRoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنحاح.
        /// </summary>
        public static string LableSave {
            get {
                return ResourceManager.GetString("LableSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف بنحاح.
        /// </summary>
        public static string LableSaveDelete {
            get {
                return ResourceManager.GetString("LableSaveDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعديل بنحاح.
        /// </summary>
        public static string LableSaveEdit {
            get {
                return ResourceManager.GetString("LableSaveEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر مجموعه المستخدم.
        /// </summary>
        public static string LableSelectUserRole {
            get {
                return ResourceManager.GetString("LableSelectUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين  الجدد.
        /// </summary>
        public static string LableUser {
            get {
                return ResourceManager.GetString("LableUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفعيل المستخدم.
        /// </summary>
        public static string LableUserActive {
            get {
                return ResourceManager.GetString("LableUserActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الاليكتروني.
        /// </summary>
        public static string LableUserEmail {
            get {
                return ResourceManager.GetString("LableUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صوره المستخدم.
        /// </summary>
        public static string LableUserImage {
            get {
                return ResourceManager.GetString("LableUserImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string LableUserName {
            get {
                return ResourceManager.GetString("LableUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم السري.
        /// </summary>
        public static string LableUserPassword {
            get {
                return ResourceManager.GetString("LableUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعد كتابه الرقم السري.
        /// </summary>
        public static string LableUseruserComparePassword {
            get {
                return ResourceManager.GetString("LableUseruserComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
    }
}
