<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\models\Register.js" />
    <Content Remove="wwwroot\models\Roles.js" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\models\Register.js" />
    <_ContentIncludedByDefault Remove="wwwroot\models\Roles.js" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Data\" />
    <Folder Include="Areas\Admin\Models\" />
    <Folder Include="wwwroot\Images\Users\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\models\Register.js" />
    <None Include="wwwroot\models\Roles.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="8.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InfraStructure\InfraStructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\ResourceBook.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ResourceBook.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\ResourceBook.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ResourceBook.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
